version: '2'
services:
  central-registry:
    env_file: .env
    ports:
     - "3001:3001"
    depends_on:
     - postgres
    networks:
     - back
  postgres:
    env_file: .env
    image: postgres:9.4
    networks:
     - back
    volumes:
     - postgres-data:/var/lib/postgresql/data
networks:
  back: {}
volumes:
  postgres-data: {}
