version: '2'
services:
  central-registry:
    image: ${DOCKER_IMAGE}:latest
    environment:
     CREG_DATABASE_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/central_registry_functional"
