version: '2'
services:
  central-end-user-registry:
    image: central-end-user-registry:latest
    environment:
     CREG_DATABASE_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
     CREG_PORT: "3001"
     CREG_HOSTNAME: "http://central-end-user-registry"

